"""create financial accounts table

Revision ID: 7f6b86902f2a
Revises: cea0aa61b86c
Create Date: 2026-08-01 20:29:53.001352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6b86902f2a'
down_revision: Union[str, Sequence[str], None] = 'cea0aa61b86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'CASH', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('include_in_cash_flow', sa.Boolean(), nullable=False),
    sa.Column('include_in_net_worth', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_active'), 'financial_accounts', ['active'], unique=False)
    op.create_index(op.f('ix_financial_accounts_user_id'), 'financial_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_accounts_user_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_active'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
